Class61Homework.Web/Models/ErrorViewModel.cs
using System;

namespace Class61Homework.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Class61Homework.Web/Models/PendingModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Class61Homework.Data;

namespace Class61Homework.Web.Models
{
    public class CandidateModelView
    {
        public IEnumerable<Person> People { get; set; }
    }
}

Class61Homework.Web/Models/PeopleStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Class61Homework.Web.Models
{
    public class PeopleStatus
    {
        public int PendingPpl { get; set; }
        public int ConfirmedPpl { get; set; }
        public int DeclinedPpl { get; set; }
    }
}

Class61Homework.Web/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Class61Homework.Web.Models;
using Class61Homework.Data;
using Microsoft.Extensions.Configuration;


namespace Class61Homework.Web.Controllers
{
    public class CandidatesController : Controller
    {
        private string _connectionString;

        public CandidatesController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Pending()
        {
            var repo = new CourseRepository(_connectionString);
            CandidateModelView mv = new CandidateModelView();
            mv.People = repo.GetPendingCandidates();

            return View(mv);
        }

        public IActionResult Confirmed()
        {
            var repo = new CourseRepository(_connectionString);
            CandidateModelView mv = new CandidateModelView();
            mv.People = repo.GetConfirmedCandidates();

            return View(mv);
        }

        public IActionResult Declined()
        {
            var repo = new CourseRepository(_connectionString);
            CandidateModelView mv = new CandidateModelView();
            mv.People = repo.GetDeclinedCandidates();

            return View(mv);
        }

        public IActionResult CandidatesStatus()
        {
            var repo = new CourseRepository(_connectionString);

            return Json(new
            {
                pendingPpl = repo.GetCountOfPendingCandidates(),
                confirmedPpl = repo.GetCountOfConfirmedCandidates(),
                declinedPpl = repo.GetCountOfDeclinedCandidates()
            });
        }

        public IActionResult ConfirmPerson(Person person)
        {
            var repo = new CourseRepository(_connectionString);
            person.Confirmed = true;
            repo.UpdatePersonStatus(person);
            IEnumerable<Person> people = repo.GetPendingCandidates();

            return Json(people);
        }

        public IActionResult DeclinePerson(Person person)
        {
            var repo = new CourseRepository(_connectionString);
            person.Confirmed = false;
            repo.UpdatePersonStatus(person);
            IEnumerable<Person> people = repo.GetPendingCandidates();

            return Json(people);
        }
    }
}

Class61Homework.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Class61Homework.Web.Models;
using Class61Homework.Data;
using Microsoft.Extensions.Configuration;

//Create an application to track potential student/candidates for an upcoming course.

//On the home page, display 4 links: Add Candidate, View Pending, View Confirmed
//and View Declined.

//When the user clicks on the Add Candidate link, they should be taken to a page
//that has a form where they can add the name, phone number and email of the
//candidate. They should also be able to add notes (e.g. some details about the
//conversation with the candidate to help remember them in the future)

//When they click on View Pending, they should be taken to a page that displays
//a list of all the pending candidates. Next to each one, display a link
//that allows the user to see that individual candidate. When they click on that link,
//they should be taken to a page that displays all the information (including the
//notes) of that candidate along with two buttons: Confirm and Decline. When either
//one of those buttons are clicked, via ajax, update the status of that candidate.

//The View Confirmed and View Declined links should take the user to a page that
//shows the confirmed/declined candidates. For extra JS practice, add a "Toggle Notes"
//button, that when clicked, shows/hides the notes column in the table.

//Finally, in the navbar of the application, there should be three links: Pending,
//Confirmed and Declined. Next to each one of those links, display a number indicating
//how many there are of each bunch. These numbers should also be updated when
//confirming/declining via Ajax.

namespace Class61Homework.Web.Controllers
{
    public class HomeController : Controller
    {
        private string _connectionString;

        public HomeController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddCandidate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCandidate(Person person)
        {
            var repo = new CourseRepository(_connectionString);
            repo.AddPerson(person);

            return Redirect("/candidates/pending");
        }
    }
}

Class61Homework.Web/Views/Candidates/Confirmed.cshtml
@using Class61Homework.Data;
@model CandidateModelView

<div class="container">
    <div class="text-center">
        <h2>Confirmed Candidates</h2>
    </div>
    <br />
    <div class="row">
        <table class="table table-bordered table-striped">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Notes</th>
            </tr>
            @foreach (Person p in Model.People)
            {
                <tr>
                    <td>@p.FirstName</td>
                    <td>@p.LastName</td>
                    <td>@p.PhoneNumber</td>
                    <td>@p.Email</td>
                    <td>@p.Notes</td>
                </tr>
            }
        </table>
    </div>
</div>

Class61Homework.Web/Views/Candidates/Declined.cshtml
@using Class61Homework.Data;
@model CandidateModelView

<div class="container">
    <div class="text-center">
        <h2>Declined Candidates</h2>
    </div>
    <br />
    <div class="row">
        <table class="table table-bordered table-striped">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Notes</th>
            </tr>
            @foreach (Person p in Model.People)
            {
                <tr>
                    <td>@p.FirstName</td>
                    <td>@p.LastName</td>
                    <td>@p.PhoneNumber</td>
                    <td>@p.Email</td>
                    <td>@p.Notes</td>
                </tr>
            }
        </table>
    </div>
</div>

Class61Homework.Web/Views/Candidates/Pending.cshtml
@using Class61Homework.Data;
@model CandidateModelView

<div class="container">
    <div class="text-center">
        <h2>Pending Candidates</h2>
    </div>
    <div class="row">
        <button id="toggle-notes" class="btn btn-primary">Toggle Notes</button>
        <br />
        <br />
        <table id="pending-ppl-table" class="table table-bordered table-striped">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th class="notes">Notes</th>
                <th>Action</th>
            </tr>
            @foreach (Person p in Model.People)
            {
                <tr>
                    <td>@p.FirstName</td>
                    <td>@p.LastName</td>
                    <td>@p.PhoneNumber</td>
                    <td>@p.Email</td>
                    <td class="notes">@p.Notes</td>
                    <td>
                        <button data-confirmid="@p.Id"
                                class="btn btn-success confirm">
                            Confirm
                        </button>
                        <button data-declineid="@p.Id"
                                class="btn btn-danger decline">
                            Decline
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@section scripts{
    <script src="~/js/PendingCandidates.js"></script>
}

Class61Homework.Web/Views/Home/AddCandidate.cshtml
<div class="container">
    <div class="text-center">
        <h2>Add New Candidate</h2>
    </div>
    <br />
    <div class="row">
        <form id="candidate-form" method="post" action="/home/addcandidate">
            <div class="col-md-4 col-md-offset-2">
                <input id="first-name" tabindex="1" type="text" name="firstname" class="form-control" placeholder="First Name" />
                <br />
                <input id="phonenumber" tabindex="3" type="text" name="phonenumber" class="form-control" placeholder="Phone Number" />
                <br />
            </div>
            <div class="col-md-4">
                <input id="last-name" tabindex="2" type="text" name="lastname" class="form-control" placeholder="Last Name" />
                <br />
                <input id="email" tabindex="4" type="text" name="email" class="form-control" placeholder="Email" />
                <br />
            </div>
            <div class="col-md-8 col-md-offset-2">
                <textarea tabindex="5" style="height:200px" type="text" name="Notes" class="form-control" placeholder="Notes"></textarea>
                <br />
                <button tabindex="6" id="add-person" disabled="disabled" type="submit" class="btn btn-success">Add Person</button>
            </div>
        </form>
    </div>
</div>

@section scripts{
    <script src="~/js/Index.js"></script>
}

Class61Homework.Web/Views/Home/Index.cshtml
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Choose what you want to do:</h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <a style="width:300px" class="btn btn-info" href="/home/addcandidate">Add a candidate</a>
            <br />
            <br />
            <a style="width:300px" class="btn btn-info" href="/candidates/pending">View pending candidates for the course</a>
            <br />
            <br />
            <a style="width:300px" class="btn btn-info" href="/candidates/confirmed">View confirmed candidates for the course</a>
            <br />
            <br />
            <a style="width:300px" class="btn btn-info" href="/candidates/declined">View declined candidates for the course</a>
        </div>
    </div>
</div>

Class61Homework.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pragramming Course</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Class61Homework.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="addcandidate">Add a New Candidate</a></li>
                    <li><a asp-area="" asp-controller="Candidates" asp-action="Pending" id="layout-pending">Pending (@ViewBag.Pending)</a></li>
                    <li><a asp-area="" asp-controller="Candidates" asp-action="Confirmed" id="layout-confirmed">Confirmed (@ViewBag.Confirmed)</a></li>
                    <li><a asp-area="" asp-controller="Candidates" asp-action="Declined" id="layout-declined">Declined (@ViewBag.Declined)</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top:20px">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>